[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.typescript"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npm run init-db"]

[start]
cmd = "npm start"

